name: 'apt-repo-builder'
description: 'Stateless, serverless APT repository manager for GitHub Releases'
author: 'etnz'
inputs:
  command:
    description: 'Command to run (index or add)'
    required: true
    default: 'add'
  config:
    description: 'Path to apt-repo-builder.yaml'
    required: false
    default: 'apt-repo-builder.yaml'
  args:
    description: 'Additional arguments for the command'
    required: false
  github_token:
    description: 'GitHub Token'
    required: true
  gpg_private_key:
    description: 'GPG Private Key to sign the repository, recommended for the "index" command, optional for the "add" command'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install apt-repo-builder
      shell: bash
      run: |
        VERSION="0.0.1"
        case $(uname -m) in
          x86_64)  URL="https://github.com/etnz/apt-repo-builder/releases/download/v$VERSION/apt-repo-builder_$VERSION_Linux_x86_64.tar.gz" ;;
          aarch64) URL="https://github.com/etnz/apt-repo-builder/releases/download/v$VERSION/apt-repo-builder_$VERSION_Linux_arm64.tar.gz" ;;
          *)       echo "::error::Unsupported architecture: $(uname -m)"; exit 1 ;;
        esac
        curl -sL "$URL" | tar xz
        sudo mv apt-repo-builder /usr/local/bin/
        chmod +x /usr/local/bin/apt-repo-builder
    
    - name: Run apt-repo-builder
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        GPG_PRIVATE_KEY: ${{ inputs.gpg_private_key }}
      run: |
        apt-repo-builder ${{ inputs.command }} --config ${{ inputs.config }} ${{ inputs.args }}

branding:
  icon: 'package'
  color: 'blue'